on:
  pull_request:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Setting up Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.3/packer_1.7.3_linux_amd64.zip
          unzip -o packer_1.7.3_linux_amd64.zip
          chmod +x packer
          sudo mv packer /usr/local/bin/

      - name: Zip Web App
        run: zip -r webapp.zip ./

      - name: Initialize Packer
        run: packer init ./main.pkr.hcl

      - name: Build the Image
        run: |
          packer build \
            -var "aws_region=${{ secrets.AWS_REGION }}" \
            -var "vpc_id=${{ secrets.VPC_ID }}" \
            -var "subnet_id=${{ secrets.SUBNET_ID }}" \
            ./main.pkr.hcl

      - name: Check the content of image_manifest.json
        run: cat image_manifest.json

      - name: Fetch the Image Name
        run: |          
          MY_MI=$(jq -r '.builds[0].artifact_id' image_manifest.json)
          echo "MY_MI=$MY_MI" >> $GITHUB_ENV

      - name: Generate Template Name with Timestamp
        id: generate-timestamp
        run: |
          echo "TNAME=webapp-ami-$(date +%Y-%m-%d-%H-%M-%S)" >> $GITHUB_ENV

      - name: Fetch AMI ID
        run: |
          AMI_ID=$(jq -r '.builds[0].artifact_id' image_manifest.json | cut -d':' -f2)
          echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV
          echo "AMI_ID set as: $AMI_ID"

      - name: Check AMI_ID in environment
        run: |
          echo "AMI_ID is: ${{ env.AMI_ID }}"

      - name: Share AMI with DEMO account
        run: |
          ACCOUNT_ID="${{ secrets.DEMO_AWS_ACCOUNT_ID }}"
          echo "Using AMI_ID: ${{ env.AMI_ID }}"
          echo "Using Account ID: $ACCOUNT_ID"
          aws ec2 modify-image-attribute \
            --image-id ${{ env.AMI_ID }} \
            --launch-permission "Add=[{UserId=$ACCOUNT_ID}]" \
            --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name:  Setting up demo environment
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEMO}}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEMO}}
            aws-region: ${{ secrets.AWS_REGION }}
            
      - name:  Configuring the launch template
        run: |
            aws --version
            aws ec2 describe-launch-templates
            aws ec2 create-launch-template-version --launch-template-data '{"ImageId":"${{ env.AMI_ID }}"}' --source-version 1 --launch-template-name ${{ secrets.LAUNCH_TEMPLATE_NAME }}
  
      - name: Instance Refresh in autoscaling group
        run: "aws autoscaling start-instance-refresh --auto-scaling-group-name ${{ secrets.AUTO_SCALING_GROUP_NAME }}"
     