name: Integration CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Integrate CI 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4